name: Build and test
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x", "8.0.x", "9.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"
          preferLatestVersion: true
      - name: Determine Version
        id: version # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: ${{ matrix.dotnet-version }}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}
      - name: Package
        run: dotnet pack --output pkg
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: BobTheBuilder.${{ steps.version.outputs.majorMinorPatch }}.nupkg
          path: pkg/BobTheBuilder.${{ steps.version.outputs.majorMinorPatch }}.nupkg
