name: Publish release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x" # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish to NuGet
        run: dotnet nuget push --api-key $NUGET_AUTH_TOKEN
